#!/bin/sh

# Zsh Plugin Update
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# Directory Navigation
alias anime='cd ~/Videos/Anime'
alias movies='cd ~/Videos/Movies'

# PostgreSQL
alias postgre='sudo -i -u postgres'

# Tmux Shortcuts
alias ta='tmux attach'
alias tk='tmux kill-server'

# Weather
alias weather='curl wttr.in'

# Kitty Terminal Update
alias kittyupdate='curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin'

# LS Aliases
alias ls='ls --color=auto --group-directories-first'            # List
alias ll='ls -alF --color=auto --group-directories-first'       # Long list with hidden files
alias la='ls -A --color=auto --group-directories-first'         # List all except . and ..
alias l='ls -CF --color=auto --group-directories-first'         # Compact list
alias las='ls -tarl --color=auto --group-directories-first'     # List, sort by modification time

# grep Aliases
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Copy clipboard to primary
alias clip='xclip -selection clipboard'

# Doom Emacs
alias doom='~/.config/emacs/bin/doom'

# Disk Usage
alias diskusage='sudo du -sh * | sort -h -r'

# Alert for Long-Running Commands
# Usage: sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Git Aliases
alias gitlog='git log --graph --oneline --decorate --all'
alias gitfzf='git log --oneline | fzf --multi --preview "git show {+1} | batcat --color=always --decorations=never"'

# Github CLI
alias copilot='gh copilot'
alias gcs='gh copilot suggest'
alias gce='gh copilot explain'

# Navigation Aliases
alias dots='cd ~/.dotfiles'
