#!/bin/zsh

# Enable version control information and colors
autoload -Uz vcs_info
autoload -U colors && colors

# Enable only git for version control
zstyle ':vcs_info:*' enable git

# Define a hook to run before each prompt
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst

# Customize version control information appearance
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' unstagedstr ' 🌟'
zstyle ':vcs_info:*' stagedstr ' 🔏'
zstyle ':vcs_info:git:*' formats "%{$fg[blue]%}git:(%{$fg[red]%}%m%{$fg[red]%}%b%{$fg[blue]%}) %c"

# Format the main prompt with hostname, current folder, and permissions.
PROMPT="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ ) %{$fg[cyan]%}%c%{$reset_color%} "
PROMPT+="\$vcs_info_msg_0_ %{$reset_color%}"

# Add a function to check for untracked files in the directory
zstyle ':vcs_info:git*+set-message:*' hooks git-untracked
+vi-git-untracked(){
    # Show a marker if there are untracked files in the Git repository
    if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) == 'true' ]] && \
        git status --porcelain | grep '??' &> /dev/null ; then
        hook_com[staged]+="%{$fg[yellow]%}💀"
    fi
}

