-- require("nvim-tree").setup({
--     sort_by = "case_sensitive",
--     view = {
--         width = 30,
--         -- auto_resize = true,
--     },
--     icons = {
--         webdev_colors = true,
--         git_placement = "before",
--         padding = " ",
--         symlink_arrow = " -> ",
--         show = {
--             file = true,
--             folder = true,
--             folder_arrow = true,
--             git = true,
--         },
--     },
--     renderer = {
--         group_empty = true,
--         special_files = { "Cargo.toml", "Makefile", "README.md", "readme.md" },
--         symlink_destination = true,
--     },
--     actions = {
--         open_file = {
--             quit_on_open = true,
--         },
--     },
--     filters = {
--         dotfiles = true,
--     },
--     update_focused_file = {
--         enable = true,
--         update_root = true,
--
--     },
-- })
--
-- vim.api.nvim_set_keymap('n', '<leader>q', ':NvimTreeToggle<cr>', { silent = true }) --Toggle tree
-- -- Transparent Background
-- vim.cmd [[hi NvimTreeNormal guibg=NONE ctermbg=NONE]]
